name: Publish Python Package

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel
      - name: Put version in environment
        id: bump
        run: |
          VERSION=${{ inputs.print_tags }}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        shell: bash
      - name: Build and publish
        run: |
          python -m build
      - uses: actions/upload-artifact@v4
        with:
          name: flytekit
          path: dist/*
